# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "4b05c1caefa9e0761a0538b64159b627"
name = "Ciwi.ai:FAT(Local)"
handle = "ciwi-local"
application_url = "https://describe-resistant-synthesis-kings.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_content,read_legal_policies,read_metaobjects,read_online_store_navigation,read_themes,read_translations,unauthenticated_read_metaobjects,unauthenticated_read_product_listings,write_locales,write_markets,write_metaobjects,write_products,write_translations"
optional_scopes = ["read_customer_events","write_pixels"]
[auth]
redirect_urls = ["https://describe-resistant-synthesis-kings.trycloudflare.com/auth/callback", "https://describe-resistant-synthesis-kings.trycloudflare.com/auth/shopify/callback", "https://describe-resistant-synthesis-kings.trycloudflare.com/api/auth/callback"]

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [
  "app_purchases_one_time/update",
  "app_subscriptions/update",
  "app/uninstalled"
]
  uri = "/webhooks"
  compliance_topics = [ "customers/data_request", "customers/redact", "shop/redact" ]

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true
