# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "4b05c1caefa9e0761a0538b64159b627"
name = "Ciwi.ai:FAT(Local)"
handle = "ciwi-local"
application_url = "https://456c2d5cf1a7.ngrok-free.app"
embedded = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [
  "app_purchases_one_time/update",
  "app_subscriptions/update",
  "app/uninstalled"
]
  uri = "/webhooks"
  compliance_topics = [ "customers/data_request", "customers/redact", "shop/redact" ]

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_content,read_legal_policies,read_markets,read_metaobjects,read_online_store_navigation,read_themes,read_translations,write_locales,write_markets,write_metaobjects,write_products,write_translations"

[auth]
redirect_urls = ["https://456c2d5cf1a7.ngrok-free.app/auth/callback", "https://456c2d5cf1a7.ngrok-free.app/auth/shopify/callback", "https://456c2d5cf1a7.ngrok-free.app/api/auth/callback"]

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true
dev_store_url = "quickstart-0f992326.myshopify.com"
