# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration
client_id = "dec512b68e658e4f21588e3d4de0e748"
name = "Ciwi.ai:FAT(Test)"
handle = "ciwi_test"
application_url = "https://typescriptfrontend.onrender.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quickstart-0f992326.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_content,read_legal_policies,read_markets,read_online_store_navigation,read_translations,write_locales,write_markets,write_products,write_translations"

[auth]
redirect_urls = [
  "https://typescriptfrontend.onrender.com/auth/callback",
  "https://typescriptfrontend.onrender.com/auth/shopify/callback",
  "https://typescriptfrontend.onrender.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

[[webhooks.subscriptions]]
topics = ["app/uninstalled", "app_purchases_one_time/update"]
uri = "/webhooks"
compliance_topics = [
  "customers/data_request",
  "customers/redact",
  "shop/redact"
]

[pos]
embedded = false
