# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "7a5eae5811d6629e9b3299748e852a6b"
name = "ZinnTransTest"
handle = "transform-lancy-app-test"
application_url = "https://absent-bennett-protection-donors.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quickstart-0f992326.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_content,read_gift_cards,read_legal_policies,read_markets,read_online_store_navigation,write_locales,write_markets,write_products,write_translations"

[auth]
redirect_urls = [
  "https://absent-bennett-protection-donors.trycloudflare.com/auth/callback",
  "https://absent-bennett-protection-donors.trycloudflare.com/auth/shopify/callback",
  "https://absent-bennett-protection-donors.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-10"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "https://costa-leu-dive-lotus.trycloudflare.com//webhooks"

[pos]
embedded = false
