# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "6e0ef7be80edbf81020e200228a86d01"
name = "ZinnTrans"
handle = "transform-lancy-app"
application_url = "https://typescriptfrontendprod.onrender.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quickstart-0f992326.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_content,read_legal_policies,read_markets,read_online_store_navigation,read_translations,write_locales,write_markets,write_products,write_translations"

[auth]
redirect_urls = [
  "https://typescriptfrontendprod.onrender.com/auth/callback",
  "https://typescriptfrontendprod.onrender.com/auth/shopify/callback",
  "https://typescriptfrontendprod.onrender.com/api/auth/callback"
]

[webhooks]
api_version = "2024-10"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "//webhooks"

[pos]
embedded = false
