# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "0269c2560f3591003453cc9bcc046598"
name = "Ciwi.ai:FAT(LocalW)"
application_url = "https://2c971c469ed8.ngrok.app"
embedded = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [
  "app_purchases_one_time/update",
  "app/uninstalled",
  "app_subscriptions/update"
]
  uri = "/webhooks"
  compliance_topics = [ "customers/data_request", "customers/redact", "shop/redact" ]

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_content,read_legal_policies,read_metaobjects,read_online_store_navigation,read_themes,read_translations,unauthenticated_read_metaobjects,unauthenticated_read_product_listings,write_locales,write_markets,write_metaobjects,write_products,write_translations"

[auth]
redirect_urls = [
  "https://2c971c469ed8.ngrok.app/auth/callback",
  "https://2c971c469ed8.ngrok.app/auth/shopify/callback",
  "https://2c971c469ed8.ngrok.app/api/auth/callback"
]

[pos]
embedded = false
