-- PlanCatalog 与 Pricing 页对齐（月度/年度订阅 + 购包 base 价；订阅购包折扣由 UI priceOverride 处理）
DELETE FROM "PlanCatalog" WHERE "planKey" LIKE 'tsf_%';

INSERT INTO "PlanCatalog" (
    "planKey",
    "kind",
    "billingInterval",
    "displayName",
    "tokens",
    "priceAmount",
    "currencyCode",
    "trialDays",
    "shopifyPlanName",
    "sortOrder",
    "enabled",
    "createdAt",
    "updatedAt"
) VALUES
    (
        'tsf_basic_monthly',
        'SUBSCRIPTION',
        'MONTHLY',
        'Basic (Monthly)',
        1500000,
        '9.99',
        'USD',
        5,
        'Basic',
        10,
        1,
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        'tsf_pro_monthly',
        'SUBSCRIPTION',
        'MONTHLY',
        'Pro (Monthly)',
        3000000,
        '29.99',
        'USD',
        5,
        'Pro',
        20,
        1,
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        'tsf_premium_monthly',
        'SUBSCRIPTION',
        'MONTHLY',
        'Premium (Monthly)',
        8000000,
        '79.99',
        'USD',
        5,
        'Premium',
        30,
        1,
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        'tsf_basic_annual',
        'SUBSCRIPTION',
        'ANNUAL',
        'Basic (Annual)',
        18000000,
        '99.99',
        'USD',
        5,
        'Basic Annual',
        11,
        1,
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        'tsf_pro_annual',
        'SUBSCRIPTION',
        'ANNUAL',
        'Pro (Annual)',
        36000000,
        '299.99',
        'USD',
        5,
        'Pro Annual',
        21,
        1,
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        'tsf_premium_annual',
        'SUBSCRIPTION',
        'ANNUAL',
        'Premium (Annual)',
        96000000,
        '799.99',
        'USD',
        5,
        'Premium Annual',
        31,
        1,
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        'tsf_pack_500k',
        'ONE_TIME_PACK',
        NULL,
        '500K Credits',
        500000,
        '3.99',
        'USD',
        NULL,
        '500K Credits',
        50,
        1,
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        'tsf_pack_1m',
        'ONE_TIME_PACK',
        NULL,
        '1M Credits',
        1000000,
        '7.99',
        'USD',
        NULL,
        '1M Credits',
        60,
        1,
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        'tsf_pack_2m',
        'ONE_TIME_PACK',
        NULL,
        '2M Credits',
        2000000,
        '15.99',
        'USD',
        NULL,
        '2M Credits',
        70,
        1,
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        'tsf_pack_3m',
        'ONE_TIME_PACK',
        NULL,
        '3M Credits',
        3000000,
        '23.99',
        'USD',
        NULL,
        '3M Credits',
        80,
        1,
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        'tsf_pack_5m',
        'ONE_TIME_PACK',
        NULL,
        '5M Credits',
        5000000,
        '39.99',
        'USD',
        NULL,
        '5M Credits',
        90,
        1,
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        'tsf_pack_10m',
        'ONE_TIME_PACK',
        NULL,
        '10M Credits',
        10000000,
        '79.99',
        'USD',
        NULL,
        '10M Credits',
        100,
        1,
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        'tsf_pack_20m',
        'ONE_TIME_PACK',
        NULL,
        '20M Credits',
        20000000,
        '159.99',
        'USD',
        NULL,
        '20M Credits',
        110,
        1,
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        'tsf_pack_30m',
        'ONE_TIME_PACK',
        NULL,
        '30M Credits',
        30000000,
        '239.99',
        'USD',
        NULL,
        '30M Credits',
        120,
        1,
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    )
ON CONFLICT("planKey") DO UPDATE SET
    "kind" = excluded."kind",
    "billingInterval" = excluded."billingInterval",
    "displayName" = excluded."displayName",
    "tokens" = excluded."tokens",
    "priceAmount" = excluded."priceAmount",
    "currencyCode" = excluded."currencyCode",
    "trialDays" = excluded."trialDays",
    "shopifyPlanName" = excluded."shopifyPlanName",
    "sortOrder" = excluded."sortOrder",
    "enabled" = excluded."enabled",
    "updatedAt" = CURRENT_TIMESTAMP;
