-- PlanCatalog：与 app/routes/app.pricing/pricingCatalog.ts 保持一致
-- 部署前清 tsf_ 套餐后全量写入；改价只改 pricingCatalog.ts 再同步本文件。

DELETE FROM "PlanCatalog" WHERE "planKey" LIKE 'tsf_%';

INSERT INTO "PlanCatalog" (
    "planKey",
    "kind",
    "billingInterval",
    "displayName",
    "tokens",
    "priceAmount",
    "currencyCode",
    "trialDays",
    "shopifyPlanName",
    "sortOrder",
    "enabled",
    "createdAt",
    "updatedAt"
) VALUES
    -- Basic Monthly: $7.99, 1,500,000 credits/month
    (
        'tsf_basic_monthly',
        'SUBSCRIPTION',
        'MONTHLY',
        'Basic (Monthly)',
        1500000,
        '7.99',
        'USD',
        5,
        'Basic',
        10,
        1,
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    -- Pro Monthly: $19.99, 3,000,000 credits/month
    (
        'tsf_pro_monthly',
        'SUBSCRIPTION',
        'MONTHLY',
        'Pro (Monthly)',
        3000000,
        '19.99',
        'USD',
        5,
        'Pro',
        20,
        1,
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    -- Premium Monthly: $39.99, 8,000,000 credits/month
    (
        'tsf_premium_monthly',
        'SUBSCRIPTION',
        'MONTHLY',
        'Premium (Monthly)',
        8000000,
        '39.99',
        'USD',
        5,
        'Premium',
        30,
        1,
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    -- Basic Yearly: $76.68/year ($6.39/mo), 1,500,000 credits/month
    (
        'tsf_basic_annual',
        'SUBSCRIPTION',
        'ANNUAL',
        'Basic (Annual)',
        1500000,
        '76.68',
        'USD',
        5,
        'Basic - Yearly',
        11,
        1,
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    -- Pro Yearly: $191.88/year ($15.99/mo), 3,000,000 credits/month
    (
        'tsf_pro_annual',
        'SUBSCRIPTION',
        'ANNUAL',
        'Pro (Annual)',
        3000000,
        '191.88',
        'USD',
        5,
        'Pro - Yearly',
        21,
        1,
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    -- Premium Yearly: $383.88/year ($31.99/mo), 8,000,000 credits/month
    (
        'tsf_premium_annual',
        'SUBSCRIPTION',
        'ANNUAL',
        'Premium (Annual)',
        8000000,
        '383.88',
        'USD',
        5,
        'Premium - Yearly',
        31,
        1,
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    -- Token packs (Free tier base price; subscriber discount at checkout via UI)
    (
        'tsf_pack_500k',
        'ONE_TIME_PACK',
        NULL,
        '500K Credits',
        500000,
        '3.99',
        'USD',
        NULL,
        '500K Credits',
        50,
        1,
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        'tsf_pack_1m',
        'ONE_TIME_PACK',
        NULL,
        '1M Credits',
        1000000,
        '7.99',
        'USD',
        NULL,
        '1M Credits',
        60,
        1,
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        'tsf_pack_2m',
        'ONE_TIME_PACK',
        NULL,
        '2M Credits',
        2000000,
        '15.99',
        'USD',
        NULL,
        '2M Credits',
        70,
        1,
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        'tsf_pack_3m',
        'ONE_TIME_PACK',
        NULL,
        '3M Credits',
        3000000,
        '23.99',
        'USD',
        NULL,
        '3M Credits',
        80,
        1,
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        'tsf_pack_5m',
        'ONE_TIME_PACK',
        NULL,
        '5M Credits',
        5000000,
        '39.99',
        'USD',
        NULL,
        '5M Credits',
        90,
        1,
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        'tsf_pack_10m',
        'ONE_TIME_PACK',
        NULL,
        '10M Credits',
        10000000,
        '79.99',
        'USD',
        NULL,
        '10M Credits',
        100,
        1,
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        'tsf_pack_20m',
        'ONE_TIME_PACK',
        NULL,
        '20M Credits',
        20000000,
        '159.99',
        'USD',
        NULL,
        '20M Credits',
        110,
        1,
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        'tsf_pack_30m',
        'ONE_TIME_PACK',
        NULL,
        '30M Credits',
        30000000,
        '239.99',
        'USD',
        NULL,
        '30M Credits',
        120,
        1,
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    );
