export const tableData = [
  {
    key: 0,
    features: "Monthly Payment",
    free: "0",
    basic: "7.99",
    pro: "19.99",
    premium: "39.99",
    type: "text",
  },
  {
    key: 1,
    features: "Annual payment discount",
    free: "",
    basic: "20%",
    pro: "20%",
    premium: "20%",
    type: "text",
  },
  {
    key: 2,
    features: "Monthly payment after discount",
    free: "",
    basic: "6.39",
    pro: "15.99",
    premium: "31.99",
    type: "text",
  },
  {
    key: 3,
    features: "Annual payment after discount",
    free: "",
    basic: "76.68",
    pro: "191.88",
    premium: "383.88",
    type: "text",
  },
  {
    key: 4,
    features: "Monthly points gift",
    free: "0",
    basic: "1,500,000 credits/month",
    pro: "3,000,000 credits/month",
    premium: "8,000,000 credits/month",
    type: "text",
  },
  {
    key: 5,
    features: "Glossary",
    free: "",
    basic: "10",
    pro: "50",
    premium: "100",
    type: "text",
  },
  {
    key: 6,
    features: "Points purchase discount",
    free: "0%",
    basic: "10%",
    pro: "25%",
    premium: "50%",
    type: "text",
  },
  {
    key: 7,
    features: "Automatic translation updates",
    free: "",
    basic: "support",
    pro: "support",
    premium: "support",
    type: "text",
  },
  {
    key: 8,
    features: "Manual Editor",
    free: "support",
    basic: "support",
    pro: "support",
    premium: "support",
    type: "text",
  },
  {
    key: 9,
    features: "Automatic IP switching",
    free: "",
    basic: "support",
    pro: "support",
    premium: "support",
    type: "text",
  },
  {
    key: 10,
    features: "IP call limit",
    free: "",
    basic: "10,000",
    pro: "25,000",
    premium: "50,000",
    type: "text",
  },
  {
    key: 11,
    features: "Third-party app translation",
    free: "",
    basic: "support",
    pro: "support",
    premium: "support",
    type: "text",
  },
  {
    key: 12,
    features: "Image Translation",
    free: "",
    basic: "support",
    pro: "support",
    premium: "support",
    type: "text",
  },
  {
    key: 13,
    features: "Private API support",
    free: "support",
    basic: "support",
    pro: "support",
    premium: "support",
    type: "text",
  },
  {
    key: 14,
    features: "Private API call limits",
    free: "30,000",
    basic: "300,000",
    pro: "800,000",
    premium: "3,000,000",
    type: "text",
  },
  {
    key: 15,
    features: "Manual support",
    free: "",
    basic: "support",
    pro: "support",
    premium: "1v1support",
    type: "text",
  },
];
