import type { ThemeConfig } from "antd";

export const appDesignTokens = {
  colorBg: "var(--p-color-bg)",
  colorSurface: "var(--p-color-bg-surface)",
  colorSurfaceSecondary: "var(--p-color-bg-surface-secondary)",
  colorSurfaceHover: "var(--p-color-bg-surface-hover)",
  colorSurfaceSelected: "var(--p-color-bg-surface-selected)",
  colorSurfaceInfo: "var(--p-color-bg-surface-info)",
  colorSurfaceSuccess: "var(--p-color-bg-surface-success)",
  colorSurfaceCaution: "var(--p-color-bg-surface-caution)",
  colorSurfaceCritical: "var(--p-color-bg-surface-critical)",
  colorBorder: "var(--p-color-border)",
  colorBorderSecondary: "var(--p-color-border-secondary)",
  colorText: "var(--p-color-text)",
  colorTextSecondary: "var(--p-color-text-secondary)",
  colorTextTertiary: "var(--p-color-text-tertiary)",
  colorBrand: "var(--p-color-bg-fill-brand)",
  colorBrandOnFill: "var(--p-color-text-brand-on-bg-fill)",
  fontSizeBody: 14,
  fontSizeBodySmall: 13,
  fontSizeCaption: 12,
  borderRadius: 8,
  borderRadiusSmall: 6,
} as const;

export const appAntdTheme: ThemeConfig = {
  token: {
    colorPrimary: appDesignTokens.colorBrand,
    colorInfo: appDesignTokens.colorBrand,
    colorSuccess: "var(--p-color-text-success)",
    colorWarning: "var(--p-color-text-caution)",
    colorError: "var(--p-color-text-critical)",
    colorText: appDesignTokens.colorText,
    colorTextSecondary: appDesignTokens.colorTextSecondary,
    colorTextHeading: appDesignTokens.colorText,
    colorBorder: appDesignTokens.colorBorder,
    colorBorderSecondary: appDesignTokens.colorBorderSecondary,
    colorBgBase: appDesignTokens.colorBg,
    colorBgContainer: appDesignTokens.colorSurface,
    colorBgElevated: appDesignTokens.colorSurface,
    colorFillAlter: appDesignTokens.colorSurfaceSecondary,
    colorSplit: appDesignTokens.colorBorderSecondary,
    fontSize: appDesignTokens.fontSizeBody,
    borderRadius: appDesignTokens.borderRadius,
    controlItemBgActive: appDesignTokens.colorSurfaceSelected,
    controlItemBgHover: appDesignTokens.colorSurfaceHover,
    wireframe: false,
  },
  components: {
    Alert: {
      colorInfoBg: appDesignTokens.colorSurfaceInfo,
      colorInfoBorder: appDesignTokens.colorBorderSecondary,
      colorSuccessBg: appDesignTokens.colorSurfaceSuccess,
      colorWarningBg: appDesignTokens.colorSurfaceCaution,
      colorErrorBg: appDesignTokens.colorSurfaceCritical,
    },
    Button: {
      borderRadius: appDesignTokens.borderRadius,
      primaryShadow: "none",
      defaultShadow: "none",
      defaultBg: appDesignTokens.colorSurface,
      defaultColor: appDesignTokens.colorText,
      defaultBorderColor: appDesignTokens.colorBorderSecondary,
      defaultHoverBg: appDesignTokens.colorSurface,
      defaultHoverColor: appDesignTokens.colorText,
      defaultHoverBorderColor: appDesignTokens.colorBrand,
      defaultActiveBg: appDesignTokens.colorSurfaceSecondary,
      defaultActiveColor: appDesignTokens.colorText,
      defaultActiveBorderColor: appDesignTokens.colorBrand,
    },
    Card: {
      colorBgContainer: appDesignTokens.colorSurface,
      headerBg: appDesignTokens.colorSurface,
      headerHeight: 42,
      headerFontSize: appDesignTokens.fontSizeBody,
      borderRadiusLG: 12,
    },
    Collapse: {
      headerBg: "transparent",
      contentBg: "transparent",
      colorBorder: appDesignTokens.colorBorderSecondary,
    },
    Input: {
      activeBg: appDesignTokens.colorSurface,
      hoverBg: appDesignTokens.colorSurface,
      activeBorderColor: appDesignTokens.colorBrand,
      hoverBorderColor: appDesignTokens.colorBorder,
      activeShadow: "0 0 0 1px rgba(0, 127, 97, 0.12)",
      addonBg: appDesignTokens.colorSurfaceSecondary,
    },
    Menu: {
      itemSelectedBg: appDesignTokens.colorSurfaceSelected,
    },
    Modal: {
      titleColor: appDesignTokens.colorText,
      titleFontSize: 16,
    },
    Select: {
      optionSelectedBg: appDesignTokens.colorSurfaceSelected,
      optionActiveBg: appDesignTokens.colorSurfaceSecondary,
      selectorBg: appDesignTokens.colorSurface,
      hoverBorderColor: appDesignTokens.colorBorder,
      activeBorderColor: appDesignTokens.colorBrand,
    },
    Statistic: {
      contentFontSize: 28,
      titleFontSize: appDesignTokens.fontSizeCaption,
    },
    Table: {
      headerBg: appDesignTokens.colorSurfaceSecondary,
      headerColor: appDesignTokens.colorTextSecondary,
      headerSplitColor: appDesignTokens.colorBorderSecondary,
      borderColor: appDesignTokens.colorBorderSecondary,
      rowHoverBg: appDesignTokens.colorSurfaceSecondary,
      rowSelectedBg: appDesignTokens.colorSurfaceSelected,
      rowSelectedHoverBg: appDesignTokens.colorSurfaceSelected,
    },
    Tabs: {
      inkBarColor: appDesignTokens.colorBrand,
      itemColor: appDesignTokens.colorTextSecondary,
      itemHoverColor: appDesignTokens.colorText,
      itemSelectedColor: appDesignTokens.colorText,
    },
    Tag: {
      defaultBg: appDesignTokens.colorSurfaceSecondary,
      defaultColor: appDesignTokens.colorTextSecondary,
      defaultBorderColor: "transparent",
    },
    Typography: {
      titleMarginBottom: 0,
      titleMarginTop: 0,
    },
  },
};
