name = "web-pixel"

uid = "bf0c0bec-8f6f-89f8-bcb1-0723c5ee9461eaf9defa"

type = "web_pixel_extension"
runtime_context = "strict"

[settings]
type = "object"

[settings.fields.shopName]
name = "Shop Name"
description = "Shop Name"
type = "single_line_text_field"
validations =  [
  { name = "min", value = "1" }
]

[settings.fields.server]
name = "Server URL"
description = "The server URL where pixel data should be sent"
type = "single_line_text_field"
validations = [
  { name = "min", value = "5" }
]