name: Deploy to Shopify on Master Update

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      # 假设你的部署命令需要商店地址和API访问令牌
      SHOPIFY_STORE: ${{ secrets.SHOPIFY_STORE }}  # 例如 'your-store.myshopify.com'
      SHOPIFY_API_ACCESS_TOKEN: ${{ secrets.SHOPIFY_API_ACCESS_TOKEN }} # 或类似的身份验证令牌
      CI: "true"  # 明确声明CI环境，避免CLI期望交互操作:cite[3]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0  # 获取所有历史记录以便查找PR提交

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'  # 建议使用LTS版本
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Install dependencies
      run: | 
        npm install -g shopify-cli
        shopify config set ci true
        shopify app info -c shopify.app.test.toml
        # 可能需要根据你的CLI版本和项目类型进行其他配置
